language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"

script:
  - "coverage erase"
  - "coverage run shop.py && coverage html"

after_success:
  - "coveralls"
