language: python

python:
  - "3.9"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install marshmallow-sqlalchemy"

script:
  - "coverage erase"
  - "coverage run -m unittest test.py"

after_success:
  - "coveralls"
